language: python
python:
    - "2.7"
    - "3.6"

env:
    - DJANGO_VERSION=1.11 DB=sqlite

# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip install -q Django==$DJANGO_VERSION


# command to run tests
before_script:
    - python manage.py makemigrations
    - python manage.py runserver &
script:
    - python manage.py migrate -v 3
    - python manage.py test -v 3
    - coverage run manage.py test -v 3
after_script:
    - coveralls
